# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
