# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('responded', models.BooleanField()),
                ('created_on', models.DateTimeField(default=datetime.datetime(2017, 2, 23, 12, 2, 2, 355887, tzinfo=utc))),
                ('modified_on', models.DateTimeField(null=True)),
                ('exited_on', models.DateTimeField(null=True)),
                ('exit_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
