# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20170223_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 2, 23, 13, 30, 56, 188467, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('node', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 2, 23, 13, 30, 56, 189081, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='values',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 13, 30, 56, 187833, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='value',
            name='run_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sync.Run'),
        ),
        migrations.AddField(
            model_name='step',
            name='run_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sync.Run'),
        ),
    ]
