# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_auto_20170223_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='contact',
            field=models.CharField(default=b'contact', max_length=200),
        ),
        migrations.AddField(
            model_name='run',
            name='flow',
            field=models.CharField(default=b'flow', max_length=200),
        ),
        migrations.AlterField(
            model_name='run',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 14, 24, 0, 616909, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='run',
            name='exit_type',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 14, 24, 0, 617597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='value',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 14, 24, 0, 618302, tzinfo=utc)),
        ),
    ]
